spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy.devdojo: debug
server:
  servlet:
    context-path: /
    # /${spring.application.name} - placeholder que pega o valor do nome do projeto.
  error:
    include-stacktrace: ON_PARAM
  tomcat:
    threads:
      max: 20